agents:
  - id: oeeAgent
    name: "OEE Executive Agent"
    description: "Provides real-time OEE reports per line, including running orders and historical benchmarks."
    trigger:
      - "oee report"
      - "oee status"
    type: "data-driven"
    priority: "high"
    oeeEnabled: true

    dataSource:
      - "oee_hot"            # neue Hot-API (MQTT Echtzeit)
      - "mock-data/orders.json"
      - "oee_history.json"   # Cold Data (Simulator / Historie)

    promptTemplate: |
      ## 📊 OEE Executive Report (Realtime + Orders + Historical Analysis)

      **1. Realtime OEE per Line (from MQTT):**
      {data.oee_hot}

      **2. Orders running on each Line:**
      {data.orders}

      **3. Historical OEE Analysis (from oee_history.json):**
      {data.oee_history}

      **4. Management Summary**
      - Compare current realtime performance vs historical trends
      - Identify lines with declining performance patterns
      - Highlight critical alarms in realtime (if present)
      - Recommend corrective actions and targets
