id: productionPlanningAgent
name: "Production Planning Agent"
agentType: "proactive"
category: "Production"
description: "Optimizes production planning by checking orders, resources and bottlenecks."
owner: "Manufacturing Team"
sla: "5s response time"
priority: "medium"

rolesAllowed:
  - Admin
  - Production
  - Planning

trigger:
  - "plan production"
  - "orders today"
  - "production schedule"
  - "delay production"

dataSource:
  - "orders"
  - "batches"

keywords:
  - "delay"
  - "reschedule"
  - "order"
  - "bottleneck"

# ⬇️ REQUIRED: Root-level promptTemplate
promptTemplate: |
  You are the Production Planning Agent for pharmaceutical manufacturing.
  
  Current Time: {timestamp}
  User Query: {userMessage}
  
  === PRODUCTION ORDERS ===
  {data.orders}
  
  === BATCH STATUS ===
  {data.batches}
  
  === INSTRUCTIONS ===
  Generate a comprehensive production planning report including:
  
  1. **Order Status** - Current production schedule and progress
  2. **Capacity Analysis** - Available capacity vs. demand
  3. **Bottleneck Identification** - Resource constraints and conflicts
  4. **Risk Assessment** - Potential delays and their impact
  5. **Optimization Recommendations** - Rescheduling and resource reallocation suggestions
  
  Format: Professional markdown with clear sections, priorities, and actionable recommendations.
  Focus: Maximize throughput while maintaining GMP compliance and quality standards.

a2aCapabilities:
  - productionSchedule
  - capacityCheck

a2aPrompts:
  productionSchedule: |
    ## A2A Request: Production Schedule
    Timestamp: {timestamp}
    Orders: {data.orders}
    
    Respond with JSON:
    {{
      "scheduledOrders": ["order1", "order2"],
      "conflicts": ["conflict description"],
      "bottlenecks": ["resource name"],
      "recommendations": ["action1", "action2"]
    }}

  capacityCheck: |
    ## A2A Request: Capacity Check
    Timestamp: {timestamp}
    Orders: {data.orders}
    Batches: {data.batches}
    
    Respond with JSON:
    {{
      "availableCapacity": 85,
      "utilizationPercent": 72,
      "overloadRisks": ["risk description"],
      "mitigationSteps": ["step1", "step2"]
    }}

events:
  subscribes:
    - "orders/created"
    - "orders/released"
  publishes:
    - "planning/updates"
    - "alerts/bottlenecks"

chainedAgents:
  - qualityAgent
  - equipmentAgent
  - oeeAgent

outputFormat:
  type: markdown
  sections:
    - title: "Order Status"
    - title: "Capacity Analysis"
    - title: "Bottlenecks"
    - title: "Risk Assessment"
    - title: "Recommendations"