id: safetyChecksAgent
name: "Safety Checks Agent"
agentType: "rule_based"
category: "Safety"
description: "Performs safety and compliance checks for batches and equipment."
owner: "EHS Team"
priority: "high"

rolesAllowed:
  - Admin
  - QA
  - Safety

trigger:
  - "safety check"
  - "safety status"

dataSource:
  - "batches"
  - "equipment"
  - "issues"

keywords:
  - "safety"
  - "risk"
  - "incident"

# ⬇️ REQUIRED: Root-level promptTemplate
promptTemplate: |
  You are the Safety Checks Agent for pharmaceutical manufacturing operations.
  
  Current Time: {timestamp}
  User Query: {userMessage}
  
  === BATCH STATUS ===
  {data.batches}
  
  === EQUIPMENT STATUS ===
  {data.equipment}
  
  === ACTIVE ISSUES ===
  {data.issues}
  
  === INSTRUCTIONS ===
  Generate a comprehensive Safety & Compliance report including:
  
  1. **Safety Status Summary** - Overall safety posture and critical alerts
  2. **Batch Safety Assessment** - Material handling risks, containment status
  3. **Equipment Safety** - Machine safeguards, lockout/tagout status, maintenance risks
  4. **Incident Analysis** - Active safety issues and their severity
  5. **Risk Assessment** - Potential hazards ranked by likelihood and impact
  6. **Mitigation Actions** - Required safety interventions with urgency levels
  
  Format: Professional markdown with clear sections.
  Focus: Worker safety, environmental protection, and regulatory compliance (OSHA, EPA, GMP).

a2aCapabilities:
  - safetyAssessment

a2aPrompts:
  safetyAssessment: |
    ## A2A Request: Safety Assessment
    Timestamp: {timestamp}
    Batches: {data.batches}
    Equipment: {data.equipment}
    Issues: {data.issues}
    
    Respond with JSON:
    {{
      "safetyStatus": "safe/warning/critical",
      "overallRiskLevel": "high/medium/low",
      "risks": [
        {{"category": "chemical/mechanical/ergonomic", "description": "...", "severity": "critical/high/medium/low"}}
      ],
      "mitigations": ["action1", "action2"]
    }}

events:
  subscribes:
    - "batch/+/status"
  publishes:
    - "alerts/safety"

chainedAgents:
  - qualityAgent
  - equipmentAgent

outputFormat:
  type: markdown
  sections:
    - title: "Safety Status Summary"
    - title: "Batch Safety"
    - title: "Equipment Safety"
    - title: "Incident Analysis"
    - title: "Risk Assessment"
    - title: "Mitigation Actions"