# Format für Production Schedule Output
structure:
  summary:
    orders_analyzed: "integer"
    released_count: "integer"
    postponed_count: "integer"
    blocked_count: "integer"
    oee_impact: "string - Overall efficiency projection"
    
  order_details:
    template:
      order_id: "string"
      material: "string"
      quantity: "string"
      market: "string"
      checks:
        bom_status: "✅|⚠️|❌"
        inventory_status: "✅|⚠️|❌"
        issues_status: "✅|⚠️|❌"
        qa_status: "✅|⚠️|❌"
        compliance_status: "✅|⚠️|❌"
        batch_status: "✅|⚠️|❌"
      decision: "RELEASED|POSTPONED|BLOCKED"
      planned_start: "date"
      oee_projection: "string"
      notes: "string"
      
  critical_points:
    template:
      issue: "string"
      severity: "CRITICAL|HIGH|MEDIUM"
      impact: "string"
      oee_impact: "string"
      
  next_steps:
    immediate: ["action items"]
    today: ["action items"]
    escalation: ["escalation items"]
    oee_optimization: ["optimization actions"]

# Beispiel Output
example:
  summary:
    orders_analyzed: 12
    released_count: 8
    postponed_count: 3
    blocked_count: 1
    oee_impact: "Overall efficiency projected at 87%"